download_dir="data/original"
urls_file="urls-present.txt"
# data_dir="/data/idiv_brose/emilio/demographic-sdm/data"
proj="proj"
eu_proj="europe.proj"
am_proj="america.proj"
# utils_file="/home/berti/demographic-sdm/R/utils.R"
