download_dir="/data/idiv_brose/emilio/chelsa/original"
urls_file="/home/berti/chelsa/urls-present.txt"
proj="proj"
eu_proj="/home/berti/chelsa/europe.proj"
am_proj="/home/berti/chelsa/america.proj"
# utils_file="/home/berti/demographic-sdm/R/utils.R"
# data_dir="/data/idiv_brose/emilio/demographic-sdm/data"
